### ISSUE TITLE
"Invalid API key. (002)" on Porkbun requests

### ISSUE THREAD

**Issue by phil-flip** [davidramiro/frigabun#12]
Hello there!
I am running into the issue that porkbun gave me an "Invalid API key. (002)" when the tool is trying to reach the endpoint. When trying it manually with the same credentials, with the "https://porkbun.com/api/json/v3/dns/retrieveByNameType" endpoint, it worked without any issues. I also tried to run it in the intended way with the executeable, but also with a self "compiled" docker image, but it will run into the same issue. I also wanted to try and test with the test utility, but I was not able to figure that out. Is there anything I'm missing?
- Phil

**Comment by davidramiro** [comment]
Closing here, your PR #13 was spot on. Thanks!
