### ISSUE TITLE
Make subdomains optional

### ISSUE THREAD

**Issue by katidiot** [davidramiro/frigabun#29]
For porkbun the DNS Create Record api states:

> name - optional
> 
> The subdomain for the record being created, not including the domain itself. Leave blank to create a record on the root domain. Use * to create a wildcard record.

Trying the configuration with * or removing the subdomain parameter throws an error _error="missing parameter"_
The functionality to create an A record on the root domain is missing because of this.
Except if there is a workaround that I am not aware of. In this case, please update the documentation.
Thanks

**Comment by davidramiro** [comment]
Great suggestion, thanks! I've implemented it and pushed a [new release](https://github.com/davidramiro/frigabun/releases/tag/v3.1.0). Should also work for Cloudflare and Gandi.
